export const dataMusic = [
  {
    id: '1',
    artist: 'The weeknd',
    track: 'Save your tears',
    poster: 'images/image1.jpg',
    mp3: 'audio/The Weeknd - Save Your Tears.mp3',
  },
  {
    id: '2',
    artist: 'Imagine Dragons',
    track: 'Follow You',
    poster: 'images/image2.jpg',
    mp3: 'audio/Imagine Dragons - Follow You.mp3',
  },
  {
    id: '3',
    artist: 'Tove Lo',
    track: 'How Long',
    poster: 'images/image3.jpg',
    mp3: 'audio/Tove Lo - How Long.mp3',
  },
  {
    id: '4',
    artist: 'Tom Odell',
    track: 'Another Love',
    poster: 'images/image4.jpg',
    mp3: 'audio/Tom Odell - Another Love.mp3',
  },
  {
    id: '5',
    artist: 'Lana Del Rey',
    track: 'Born To Die',
    poster: 'images/image5.jpg',
    mp3: 'audio/Lana Del Rey - Born To Die.mp3',
  },
  {
    id: '6',
    artist: 'Adele',
    track: 'Hello',
    poster: 'images/image6.jpg',
    mp3: 'audio/Adele - Hello.mp3',
  },
  {
    id: '7',
    artist: 'Tom Odell',
    track: "Can't Pretend",
    poster: 'images/image7.jpg',
    mp3: "audio/Tom Odell - Can't Pretend.mp3",
  },
  {
    id: '8',
    artist: 'Lana Del Rey',
    track: 'Young And Beautiful',
    poster: 'images/image8.jpg',
    mp3: 'audio/Lana Del Rey - Young And Beautiful.mp3',
  },
  {
    id: '9',
    artist: 'Adele',
    track: 'Someone Like You',
    poster: 'images/image9.jpg',
    mp3: 'audio/Adele - Someone Like You.mp3',
  },
  {
    id: '10',
    artist: 'Imagine Dragons',
    track: 'Natural',
    poster: 'images/image10.jpg',
    mp3: 'audio/Imagine Dragons - Natural.mp3',
  },
  {
    id: '11',
    artist: 'Drake',
    track: 'Laugh Now Cry Later',
    poster: 'images/image11.jpg',
    mp3: 'audio/Drake - Laugh Now Cry Later.mp3',
  },
  {
    id: '12',
    artist: 'Madonna',
    track: 'Frozen',
    poster: 'images/image12.jpg',
    mp3: 'audio/Madonna - Frozen.mp3',
  },
  {
    id: '13',
    artist: 'Daniel Leggs',
    track: 'Crutches',
    poster: 'images/image13.jpg',
    mp3: 'audio/Daniel Leggs - crutches.mp3',
  },
  {
    id: '14',
    artist: 'Samuel Jack',
    track: 'Trouble',
    poster: 'images/image14.jpg',
    mp3: 'audio/Samuel Jack - Trouble.mp3',
  },
  {
    id: '15',
    artist: 'Xolidayboy',
    track: 'Моя хулиганка',
    poster: 'images/image15.jpg',
    mp3: 'audio/Xolidayboy - Моя хулиганка.mp3',
  },
  {
    id: '16',
    artist: 'Imagine Dragons',
    track: 'Bones',
    poster: 'images/image16.jpg',
    mp3: 'audio/Imagine Dragons - Bones.mp3',
  },
  {
    id: '17',
    artist: 'Chymes',
    track: 'All Time Low',
    poster: 'images/image17.jpg',
    mp3: 'audio/Chymes - All Time Low.mp3',
  },
];